Actualizacion participante
FaruNL/residencia pull request #20
Opened 2022-04-25 07:50 UTC by SergioRamire

2022-04-25 07:54 UTC, Natali-Rojas submitted a review, later dismissed

2022-04-25 08:02 UTC, RouterUIZ007 approved these changes

2022-04-25 15:14 UTC, FaruNL requested changes
Además el coomit f2162c4d20862850aaa9c956b8aa71ffab53567d es innecesario: 
- `<tab>` de diferencia en un comentario
- Se añadió un archivo `*.diff` que no debería ir

2022-04-25 15:14 UTC, FaruNL commented on app/Http/Livewire/Admin/ParticipantController.php
> +            'correo_tecnm' => ['email', 'regex:/(.*)@oaxaca\.tecnm\.mx$/i'],
Falta la validación `required`.

Y podemos reemplazar el regex por `'ends_with:@itoaxaca.edu.mx'` y `'ends_with:@oaxaca.tecnm.mx'` respectivamente. Así el mensaje de error es más claro y les dirá que esa debe de ser la terminación del correo.

2022-04-25 15:14 UTC, FaruNL commented on app/Http/Livewire/Admin/ParticipantController.php
> +            'area_id' => 'required',
Falta la validación `'exists:areas,id'`.

Esto para que no venga un listillo, edite la página _(temporalmente)_ desde su navegador y añada otra opción. De esta forma nos aseguramos que sólo sean válidos los valores que coincidan con el `id` de `areas` en la BD.

2022-04-25 15:14 UTC, FaruNL commented on resources/views/components/sidebar.blade.php
> +                        <x-sidebar.link href="#" class="pl-11">Permisos</x-sidebar.link>
Estos eran los nombres anteriores, por lo que son incorrectos, las líneas eliminadas eran las correctas:

```blade
<x-sidebar.link :href='route("{$route}users")' :active='request()->routeIs("{$route}users")' class="pl-11">Listar</x-sidebar.link>
<x-sidebar.link :href='route("{$route}users.roles")' class="pl-11">Configurar roles</x-sidebar.link>
```

2022-04-25 15:14 UTC, FaruNL commented on resources/views/components/sidebar.blade.php
> +                        <x-sidebar.link href="#" class="pl-11">Permisos</x-sidebar.link>
Estos eran los nombres anteriores, por lo que son incorrectos, las líneas eliminadas eran las correctas:

```blade
<x-sidebar.link :href='route("{$route}users")' :active='request()->routeIs("{$route}users")' class="pl-11">Listar</x-sidebar.link>
<x-sidebar.link :href='route("{$route}users.roles")' class="pl-11">Configurar roles</x-sidebar.link>
```

2022-04-25 16:27 UTC, Natali-Rojas commented on app/Http/Livewire/Admin/ParticipantController.php
> +                        ->orWhere(DB::raw("concat(participants.nombre,' ',participants.apellido_paterno,' ', participants.apellido_materno)"), 'like', '%'.$this->search.'%');
Hola Fa, pues mira nosotros contemplábamos que el usuario buscara no solo una palabra que vendría siendo ya sea nombre apellido pater o mater, que tal si pone "Mareli [espacio] Rojas", o todo su nombre, por lo cual nos pareció adecuada esa búsqueda

2022-04-25 16:38 UTC, SergioRamire commented on app/Http/Livewire/Admin/ParticipantController.php
> +            'curp' => ['required', 'regex:/^([A-ZÑ&]|[a-zñ&]{1})([AEIOU]|[aeiou]{1})([A-Z&]|[a-z&]{1})([A-Z&]|[a-z&]{1})([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])([HM]|[hm]{1})([AS|as|BC|
Aaaa si ya habia yo revisado esta Expresión, pero lo que pasa es que ese alfabeto que estamos poniendo en esa expresión, no contempla la letra "Ñ", así que cuando una curp traiga la letra "Ñ" no lo va a considerar, por eso tuve que buscar y modificar una expresión que considere esa letra

2022-04-25 16:41 UTC, SergioRamire commented on app/Http/Livewire/Admin/ParticipantController.php
> +            'rfc' => ['required', 'regex:/^[A-ZÑ&]{3,4}\d{6}(?:[A-Z\d]{3})?$/'],
aaa pero aqui el detalle con esta Expresion es que esta diseñada para un RFC de esta naturaleza: KXB-710522-IL6, pero usualmente los RFC, no deben de llevar el guion medio (-), debe de ir todo junto, es decir: KXB710522IL6.

Es por eso se utiliza la expresión regular del RFC pero sin el guión..........

2022-04-26 03:14 UTC, Natali-Rojas approved these changes

2022-04-26 03:44 UTC, Natali-Rojas submitted a review, later dismissed

2022-04-26 04:03 UTC, Natali-Rojas submitted a review, later dismissed

2022-04-26 04:07 UTC, RouterUIZ007 approved these changes

2022-04-26 04:13 UTC, Natali-Rojas commented
> Además el coomit [f2162c4](https://github.com/FaruNL/residencia/commit/f2162c4d20862850aaa9c956b8aa71ffab53567d) es innecesario:
> 
> * `<tab>` de diferencia en un comentario
> * Se añadió un archivo `*.diff` que no debería ir

2022-04-26 04:18 UTC, SergioRamire commented
> Además el coomit [f2162c4](https://github.com/FaruNL/residencia/commit/f2162c4d20862850aaa9c956b8aa71ffab53567d) es imprescindible:
> 
> * `<tab>`de diferencia en un comentario
> * Se añadió un archivo `*.diff`que no debería ir

a

2022-04-26 22:30 UTC, FaruNL submitted a review, later dismissed

2022-04-26 22:59 UTC, Natali-Rojas approved these changes

2022-04-26 23:00 UTC, FaruNL approved these changes

2022-04-27 02:54 UTC, FaruNL commented
Integrado con ayuda del PR #25

2022-04-27 02:54 UTC, closed without merging